spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ifood
    username: postgres
    password: ifood123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    maximum-pool-size: 10
external:
  api:
    url: https://jsonplaceholder.typicode.com/photos